/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['"Plus Jakarta Sans"', 'Inter', 'sans-serif'],
        hand: ['Caveat', 'cursive'],
      },
      colors: {
        ai: {
          bg: '#05080f',
          bg2: '#0a0f1e',
          card: '#0d1223',
          primary: '#4f8ef7',
          purple: '#7c5cf6',
          cyan: '#06b6d4',
          green: '#10b981',
          pink: '#ec4899',
        },
      },
      animation: {
        'pulse-slow': 'pulseSlow 8s ease-in-out infinite',
        'float-y': 'floatY 5s ease-in-out infinite',
        'spin-slow': 'spin 20s linear infinite',
        'spin-slower': 'spin 35s linear infinite reverse',
        'blink': 'blink 900ms steps(2,start) infinite',
        'slide-down': 'slideDown 0.28s ease both',
        'fade-in-up': 'fadeInUp 0.7s ease both',
        'fade-in-left': 'fadeInLeft 0.8s ease both',
        'fade-in-right': 'fadeInRight 0.8s ease both',
        'particle': 'particleDrift 5s ease-in-out infinite',
        'glow-border': 'glowBorder 3s ease-in-out infinite',
        'shimmer': 'shimmer 2.5s linear infinite',
        'neural': 'neuralPulse 4s ease-in-out infinite',
      },
      keyframes: {
        pulseSlow: { '0%,100%': { opacity: '0.55', transform: 'scale(1)' }, '50%': { opacity: '0.85', transform: 'scale(1.08)' } },
        floatY: { '0%,100%': { transform: 'translateY(0) rotate(-1deg)' }, '50%': { transform: 'translateY(-18px) rotate(1deg)' } },
        blink: { '0%,100%': { opacity: '1' }, '50%': { opacity: '0' } },
        slideDown: { from: { opacity: '0', transform: 'translateY(-12px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        fadeInUp: { from: { opacity: '0', transform: 'translateY(32px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        fadeInLeft: { from: { opacity: '0', transform: 'translateX(-40px)' }, to: { opacity: '1', transform: 'translateX(0)' } },
        fadeInRight: { from: { opacity: '0', transform: 'translateX(40px)' }, to: { opacity: '1', transform: 'translateX(0)' } },
        particleDrift: { '0%,100%': { transform: 'translateY(0) translateX(0)', opacity: '0.5' }, '50%': { transform: 'translateY(-28px) translateX(12px)', opacity: '1' } },
        glowBorder: { '0%,100%': { borderColor: 'rgba(79,142,247,0.2)' }, '50%': { borderColor: 'rgba(79,142,247,0.6)' } },
        shimmer: { '0%': { backgroundPosition: '-200% center' }, '100%': { backgroundPosition: '200% center' } },
        neuralPulse: { '0%,100%': { opacity: '0.2', r: '3' }, '50%': { opacity: '1', r: '5' } },
      },
      boxShadow: {
        'ai-sm': '0 4px 16px rgba(0,0,0,0.45)',
        'ai-md': '0 10px 40px rgba(0,0,0,0.5)',
        'ai-glow': '0 0 40px rgba(79,142,247,0.2)',
        'ai-card': '0 8px 32px rgba(0,0,0,0.5), 0 1px 0 rgba(255,255,255,0.06) inset',
        'glow-blue': '0 0 24px rgba(79,142,247,0.5), 0 0 8px rgba(79,142,247,0.3)',
        'glow-purple': '0 0 24px rgba(124,92,246,0.5)',
        'glow-cyan': '0 0 22px rgba(6,182,212,0.4)',
      },
      backgroundImage: {
        'ai-grid': "linear-gradient(rgba(79,142,247,0.06) 1px, transparent 1px), linear-gradient(90deg, rgba(79,142,247,0.06) 1px, transparent 1px)",
        'grad-primary': 'linear-gradient(135deg, #4f8ef7 0%, #7c5cf6 100%)',
        'grad-accent': 'linear-gradient(135deg, #06b6d4 0%, #4f8ef7 100%)',
        'grad-warm': 'linear-gradient(135deg, #ec4899 0%, #7c5cf6 100%)',
        'grad-shimmer': 'linear-gradient(90deg, transparent 0%, rgba(255,255,255,0.1) 50%, transparent 100%)',
      },
    },
  },
  plugins: [],
};
